service: tesco-keto-api # NOTE: Don't put the word "google" in here

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: europe-west1
  project: tesco-keto-api
  credentials: .gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  homepage:
    handler: homepage
    events:
      - http: path
        path: /
        method: GET
    include:
      - .next/**
      - pages/**
  products:
    handler: products
    events:
      - http: path
        path: /api/products
        method: GET
    environmentVariables:
      TESCO_SUBSCRIPTION_KEY: ${env.TESCO_SUBSCRIPTION_KEY}


