version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/tesco-keto-api

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run bootstrap
      - run: echo "TESCO_API_KEY=${TESCO_API_KEY}" >> ./.env
      - run: echo "NODE_ENV=production" >> ./.env
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:unit:ci
      - store_test_results:
          path: ./test-results

  webapp:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - run: cd packages/webapp && npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - run: mkdir .gcloud
      - run: echo $GCLOUD_KEY > .gcloud/keyfile.json
      - run: npm run deploy

workflows:
  version: 2.1
  release:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
          filters:
            branches:
              only: master
      - webapp:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - webapp
          filters:
            branches:
              only: master
